### ISSUE TITLE
Installing PyTango on Ubuntu 17.04

### ISSUE THREAD

**Issue by andygotz** [tango-controls/pytango#107]
I have tried to use pip install to install the latest version of pytango on my newly upgraded Ubuntu 17.04. Both the Python2 and Python3 version fail with these errors:

1. Python2 - "pip install pytango" fails with this error after compiling everything:

    /usr/bin/ld: cannot find -lboost_python-py35
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1

2. Python3 - "pip install pytango3"does not even start the download and fails with this error:

  Collecting pytango3
  Could not find a version that satisfies the requirement pytango3 (from versions: )
  No matching distribution found for pytango3

Thanks for any ideas or help on what the problem could be ...

Andy

**Comment by andygotz** [comment]
I need to use pip install because the debian packages for pytango in Ubuntu 17.04 seem to be broken ...

**Comment by vxgmichel** [comment]
Hi Andy,

I'm not so familiar with Ubuntu 17, could you run the following commands and paste the output?

    $ pip -V
    $ pip2 -V
    $ pip3 -V
    $ find /usr/lib -name libboost_python*
    $ apt search boost-python

Thanks!

**Comment by andygotz** [comment]
Hi Vincent,
here is the output:

goetz@pcandy:/etc/init.d$ pip -V
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
goetz@pcandy:/etc/init.d$ pip2 -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
goetz@pcandy:/etc/init.d$ pip3 -V
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
goetz@pcandy:/etc/init.d$ find /usr/lib -name libboost_python*
/usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.62.0
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.62.0

Thanks for your help!
Andy

**Comment by vxgmichel** [comment]
Great, now can you run:

    $ apt search boost-python
    $ dpkg -S boost_python

Thanks

**Comment by andygotz** [comment]
goetz@pcandy:/etc/init.d$ apt search boost-python
Sorting... Done
Full Text Search... Done
libboost-python-dev/zesty 1.62.0.1 amd64
  Boost.Python Library development files (default version)

libboost-python1.55.0/now 1.55.0+dfsg-3ubuntu2 amd64 [residual-config]
  (none)

libboost-python1.61-dev/zesty 1.61.0+dfsg-3build1 amd64
  Boost.Python Library development files

libboost-python1.61.0/zesty 1.61.0+dfsg-3build1 amd64
  Boost.Python Library

libboost-python1.62-dev/zesty 1.62.0+dfsg-4 amd64
  Boost.Python Library development files

libboost-python1.62.0/zesty,now 1.62.0+dfsg-4 amd64 [installed,auto-removable]
  Boost.Python Library

libboost-python1.63-dev/zesty 1.63.0+dfsg-1 amd64
  Boost.Python Library development files

libboost-python1.63.0/zesty 1.63.0+dfsg-1 amd64
  Boost.Python Library

goetz@pcandy:/etc/init.d$ dpkg -S boost_python
libboost-python1.62.0: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.62.0
libboost-python1.62.0: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.62.0

**Comment by vxgmichel** [comment]
Thanks Andy,

First you need to install `libboost-python1.62-dev`:

     $ sudo apt install libboost-python1.62-dev

Then install pytango for python2:

    $ sudo pip2 install pytango

And pytango for python3:

    $ sudo pip3 install pytango

Note that `pip` points to `pip3`. You might want to run the same check for `python` (`python -V`).

**Comment by andygotz** [comment]
Vincent, thanks for the instructions. I thought i had installed libboost-dev but obviously not libboost-python-dev. After doing as you told I have a new problem. pip2 install pytango fails with the error below. I have checked the disk space and there is enough. Any ideas?

   copying /tmp/pip-build-0BYWXp/pytango/build/sphinx/html/green.html -> /usr/local/share/doc/pytango/html
    copying /tmp/pip-build-0BYWXp/pytango/build/sphinx/html/quicktour.html -> /usr/local/share/doc/pytango/html
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0BYWXp/pytango/setup.py", line 557, in <module>
        main()
      File "/tmp/pip-build-0BYWXp/pytango/setup.py", line 554, in main
        return setup(**setup_args())
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 620, in run
        outputs = self.get_outputs()
      File "/usr/lib/python2.7/distutils/command/install.py", line 663, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
        raise AttributeError, attr
    AttributeError: get_outputs
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0BYWXp/pytango/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h4F7rW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0BYWXp/pytango/

**Comment by andygotz** [comment]
I also seem to have old versions of PyTango in /usr/local/python2.7:

drwxr-sr-x  4 root staff    4096 nov.  26  2015 PyTango
drwxr-sr-x  2 root staff    4096 mai    8 13:42 pytango-9.2.1.egg-info
-rw-r--r--  1 root staff    1478 août  18  2016 PyTango.py
-rw-r--r--  1 root staff    1402 mai    8 13:42 PyTango.pyc

Maybe I should remove these first?

**Comment by vxgmichel** [comment]
The error you report is a known issue, that has been fixed right after the pytango-9.2.1 release. However, it shouldn't prevent pytango to be installed correctly. Can you try:

    $ python2 -c "import tango; print(tango.Release.version)"

**Comment by andygotz** [comment]
You are right - it works! Cool I have pytango up and running again thanks to you!

Thanks for all your help!

Andy

**Comment by vxgmichel** [comment]
Cool! What about the python3 installation? 

Maybe the "Getting started" section of the documentation should have been more detailed.

Also, we should probably release 9.2.2 so people don't get too confused with the error you reported.

**Comment by andygotz** [comment]
Works as well. Displays the same error at the end. Yes I agree it is confusing so a new release will be welcome. At the latest by the Tango meeting in Florence.

**Comment by jyotinpo** [comment]
Hi @vxgmichel, @andygotz,

Today I upgraded/installed PyTango 9.2.5 on Ubuntu 16.04 with for Python2/Python3 respectively. I got the same error (AttributeError: get_outputs) which @andygotz reported. I assumed that it shall be resolved in PyTango 9.2.5 but it is still appearing. However, the import is working fine with the updated PyTango version (9.2.5) and hence, I am ignoring the error.

Kind regards,
Jyotin
